### ISSUE TITLE
特定情况下时钟文字部分超出页面

### ISSUE THREAD

**Issue by aixiademozhuzi** [Yuns-Lab/JingHaiWeb#4]
### 检查项

- [X] 我已在 [Issues 页面](https://github.com/Yuns-Lab/JingHaiWeb/issues) 中搜索，确认了这一建议未被提交过。
- [X] 我已查看 [功能投票页面](https://github.com/Yuns-Lab/JingHaiWeb/discussions/categories/%E6%8A%95%E7%A5%A8)，确认了这一建议未在投票列表中。

### 描述

![UTFJEK)$8QX8V_}IGNF6M2N](https://github.com/Yuns-Lab/JingHaiWeb/assets/150514687/6e474a54-96ae-4823-bacf-7e5d57ff70e1)

### 原因

1

### 意向调查

- [ ] 我愿意为此反馈做出贡献

**Comment by JingHai-Lingyun** [comment]
哎，非标准长宽（1920 × 1080）屏幕下 NavBar 又坏了..............
一个 Bug 修两遍了要 :joy:
